# Generated by Django 3.0.5 on 2020-06-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app18', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModels',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
